#!/usr/bin/env bash

set -euo pipefail

function getPRs() {
    echo $(curl -sSg \
        -u apikey:${GITHUB_TOKEN} \
        -H 'Accept: application/vnd.github.v3+json' \
        -H 'Content-Type: application/json' \
        -X GET \
        "https://api.github.com/search/issues?q=${BUILDKITE_COMMIT}+type%3Apr+is%3Aopen+repo%3A${GITHUB_USER}%2F${GITHUB_REPO}" | jq -j '.items | map(.number) | .[]')
}

function addComment() {
    local PR=$1

    echo "~~~ Posting comment to PR $PR"

    jq -n --arg msg "${BUILDKITE_PLUGIN_GITHUB_PR_COMMENT_COMMENT}" '{body: $msg}' | curl -sSg \
        -u apikey:${GITHUB_TOKEN} \
        -H 'Accept: application/vnd.github.v3+json' \
        -H 'Content-Type: application/json' \
        -X POST \
        -d@- \
        "https://api.github.com/repos/${GITHUB_USER}/${GITHUB_REPO}/issues/${PR}/comments"
}

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "Error: GITHUB_TOKEN environment variable not set"
  echo "A Github personal access token with repo permissions is needed to comment on pull requests"
  exit 1
fi

re="^(https|git)(:\/\/|@)([^\/:]+)[\/:]([^\/:]+)\/(.+).git$"

if [[ $BUILDKITE_REPO =~ $re ]]; then
    GITHUB_USER=${BASH_REMATCH[4]}
    GITHUB_REPO=${BASH_REMATCH[5]}
fi

env

for PR in $(getPRs); do
    addComment $PR
done
